### ISSUE TITLE
make faliure

### ISSUE THREAD

**Issue by HazemAbaza91** [DLR-SC/tasking-framework#2]
Running make lib command result in : build/taskStatistics.d:3: *** missing separator.  Stop.

**Comment by OMaSpace** [comment]
Thank you for your failure report.
This behaviour of the makefile is known and fixed in version 1.0.1. 

Reasoning was the default setting of the `echo` command with escapes on. After a Linux update in our build environment, the default of `echo` was escapes off. Now echo use the `-e` option to be independent of default settings in the `echo` call when escapes shall expand.
